/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const CategorySubcategoriesListParams = zod.object({
  categoryId: zod.number(),
});

export const CategorySubcategoriesListResponseItem = zod.object({
  id: zod.number().min(1),
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});
export const CategorySubcategoriesListResponse = zod.array(
  CategorySubcategoriesListResponseItem,
);

export const CategorySubcategoriesCreateParams = zod.object({
  categoryId: zod.number(),
});

export const CategorySubcategoriesCreateBody = zod.object({
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});

export const CategorySubcategoriesCreateResponse = zod.object({
  id: zod.number().min(1),
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});

export const CategorySubcategoriesGetParams = zod.object({
  categoryId: zod.number(),
  subcategoryId: zod.number(),
});

export const CategorySubcategoriesGetResponse = zod.object({
  id: zod.number().min(1),
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});

export const CategorySubcategoriesDeleteParams = zod.object({
  categoryId: zod.number(),
  subcategoryId: zod.number(),
});
