/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const accountsListResponseItem = zod.object({
  id: zod.number().min(1),
  name: zod.string().min(1),
  ownerId: zod.number().min(1),
  createdAt: zod.iso.datetime({}),
});
export const accountsListResponse = zod.array(accountsListResponseItem);

export const accountsRedeemInvitationBody = zod.object({
  code: zod.string(),
});

export const accountsRedeemInvitationResponse = zod.object({
  id: zod.number().min(1),
  code: zod.string(),
  accountId: zod.number().min(1),
  expiresAt: zod.iso.datetime({}),
  usedAt: zod.iso.datetime({}).optional(),
  usedBy: zod.number().min(1).optional(),
});

export const accountsCreateInvitationParams = zod.object({
  accountId: zod.number(),
});

export const accountsCreateInvitationResponse = zod.object({
  id: zod.number().min(1),
  code: zod.string(),
  accountId: zod.number().min(1),
  expiresAt: zod.iso.datetime({}),
  usedAt: zod.iso.datetime({}).optional(),
  usedBy: zod.number().min(1).optional(),
});
