/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const accountsListResponseItem = zod.object({
  id: zod.number().min(1),
  name: zod.string().min(1),
  ownerId: zod.number().min(1),
  createdAt: zod.iso.datetime({}),
});
export const accountsListResponse = zod.array(accountsListResponseItem);
