/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AccountDTO,
  AccountIdDTO,
  AccountInvitationDTO,
  AccountUpdateDTO,
  ForbiddenErrorDTO,
  InternalServerErrorDTO,
  InvitationNotFoundErrorDTO,
  NotFoundErrorDTO,
  RedeemInvitationRequestDTO,
  UnauthorizedErrorDTO,
} from ".././model";

import { fetcher } from "../../fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAccountsListUrl = () => {
  return `/api/v1/accounts`;
};

export const accountsList = async (
  options?: RequestInit,
): Promise<AccountDTO[]> => {
  return fetcher<AccountDTO[]>(getAccountsListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAccountsListQueryKey = () => {
  return ["accountsList"] as const;
};

export const getAccountsListQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountsListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountsList>>> = ({
    signal,
  }) => accountsList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccountsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsList>>
>;
export type AccountsListQueryError = NotFoundErrorDTO | InternalServerErrorDTO;

export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountsList>>,
          TError,
          Awaited<ReturnType<typeof accountsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountsList>>,
          TError,
          Awaited<ReturnType<typeof accountsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAccountsListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateAccountsList = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getAccountsListQueryKey() },
    options,
  );

  return queryClient;
};

export const getAccountsRedeemInvitationUrl = () => {
  return `/api/v1/accounts/invitations/redeem`;
};

export const accountsRedeemInvitation = async (
  redeemInvitationRequestDTO: RedeemInvitationRequestDTO,
  options?: RequestInit,
): Promise<AccountInvitationDTO> => {
  return fetcher<AccountInvitationDTO>(getAccountsRedeemInvitationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(redeemInvitationRequestDTO),
  });
};

export const getAccountsRedeemInvitationMutationOptions = <
  TError =
    | UnauthorizedErrorDTO
    | InvitationNotFoundErrorDTO
    | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsRedeemInvitation>>,
    TError,
    { data: RedeemInvitationRequestDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsRedeemInvitation>>,
  TError,
  { data: RedeemInvitationRequestDTO },
  TContext
> => {
  const mutationKey = ["accountsRedeemInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsRedeemInvitation>>,
    { data: RedeemInvitationRequestDTO }
  > = (props) => {
    const { data } = props ?? {};

    return accountsRedeemInvitation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsRedeemInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsRedeemInvitation>>
>;
export type AccountsRedeemInvitationMutationBody = RedeemInvitationRequestDTO;
export type AccountsRedeemInvitationMutationError =
  | UnauthorizedErrorDTO
  | InvitationNotFoundErrorDTO
  | InternalServerErrorDTO;

export const useAccountsRedeemInvitation = <
  TError =
    | UnauthorizedErrorDTO
    | InvitationNotFoundErrorDTO
    | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountsRedeemInvitation>>,
      TError,
      { data: RedeemInvitationRequestDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountsRedeemInvitation>>,
  TError,
  { data: RedeemInvitationRequestDTO },
  TContext
> => {
  const mutationOptions = getAccountsRedeemInvitationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getAccountsUpdateUrl = (accountId: AccountIdDTO) => {
  return `/api/v1/accounts/${accountId}`;
};

export const accountsUpdate = async (
  accountId: AccountIdDTO,
  accountUpdateDTO: AccountUpdateDTO,
  options?: RequestInit,
): Promise<AccountDTO> => {
  return fetcher<AccountDTO>(getAccountsUpdateUrl(accountId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(accountUpdateDTO),
  });
};

export const getAccountsUpdateMutationOptions = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsUpdate>>,
    TError,
    { accountId: AccountIdDTO; data: AccountUpdateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsUpdate>>,
  TError,
  { accountId: AccountIdDTO; data: AccountUpdateDTO },
  TContext
> => {
  const mutationKey = ["accountsUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsUpdate>>,
    { accountId: AccountIdDTO; data: AccountUpdateDTO }
  > = (props) => {
    const { accountId, data } = props ?? {};

    return accountsUpdate(accountId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsUpdate>>
>;
export type AccountsUpdateMutationBody = AccountUpdateDTO;
export type AccountsUpdateMutationError =
  | UnauthorizedErrorDTO
  | ForbiddenErrorDTO
  | InternalServerErrorDTO;

export const useAccountsUpdate = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountsUpdate>>,
      TError,
      { accountId: AccountIdDTO; data: AccountUpdateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountsUpdate>>,
  TError,
  { accountId: AccountIdDTO; data: AccountUpdateDTO },
  TContext
> => {
  const mutationOptions = getAccountsUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getAccountsCreateInvitationUrl = (accountId: number) => {
  return `/api/v1/accounts/${accountId}/invitations`;
};

export const accountsCreateInvitation = async (
  accountId: number,
  options?: RequestInit,
): Promise<AccountInvitationDTO> => {
  return fetcher<AccountInvitationDTO>(
    getAccountsCreateInvitationUrl(accountId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getAccountsCreateInvitationMutationOptions = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsCreateInvitation>>,
    TError,
    { accountId: number },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsCreateInvitation>>,
  TError,
  { accountId: number },
  TContext
> => {
  const mutationKey = ["accountsCreateInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsCreateInvitation>>,
    { accountId: number }
  > = (props) => {
    const { accountId } = props ?? {};

    return accountsCreateInvitation(accountId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsCreateInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsCreateInvitation>>
>;

export type AccountsCreateInvitationMutationError =
  | UnauthorizedErrorDTO
  | ForbiddenErrorDTO
  | InternalServerErrorDTO;

export const useAccountsCreateInvitation = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountsCreateInvitation>>,
      TError,
      { accountId: number },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountsCreateInvitation>>,
  TError,
  { accountId: number },
  TContext
> => {
  const mutationOptions = getAccountsCreateInvitationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
