/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AccountDTO, NotFoundErrorDTO } from ".././model";

import { customFetcher } from "../../customFetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAccountsListUrl = () => {
  return `/api/v1/accounts`;
};

export const accountsList = async (
  options?: RequestInit,
): Promise<AccountDTO[]> => {
  return customFetcher<AccountDTO[]>(getAccountsListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAccountsListQueryKey = () => {
  return ["accountsList"] as const;
};

export const getAccountsListQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountsListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountsList>>> = ({
    signal,
  }) => accountsList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccountsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsList>>
>;
export type AccountsListQueryError = NotFoundErrorDTO;

export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountsList>>,
          TError,
          Awaited<ReturnType<typeof accountsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountsList>>,
          TError,
          Awaited<ReturnType<typeof accountsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAccountsList<
  TData = Awaited<ReturnType<typeof accountsList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof accountsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAccountsListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateAccountsList = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getAccountsListQueryKey() },
    options,
  );

  return queryClient;
};
