/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Category,
  CategoryCreate,
  InternalServerError,
  NotFoundError,
  ValidationError
} from '../../../../model';





export type categoriesListResponse200 = {
  data: Category[]
  status: 200
}

export type categoriesListResponse404 = {
  data: NotFoundError
  status: 404
}
    
export type categoriesListResponseSuccess = (categoriesListResponse200) & {
  headers: Headers;
};
export type categoriesListResponseError = (categoriesListResponse404) & {
  headers: Headers;
};

export type categoriesListResponse = (categoriesListResponseSuccess | categoriesListResponseError)

export const getCategoriesListUrl = () => {


  

  return `/api/v1/categories`
}

export const categoriesList = async ( options?: RequestInit): Promise<categoriesListResponse> => {
  
  const res = await fetch(getCategoriesListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categoriesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categoriesListResponse
}





export const getCategoriesListQueryKey = () => {
    return [
    `/api/v1/categories`
    ] as const;
    }

    
export const getCategoriesListQueryOptions = <TData = Awaited<ReturnType<typeof categoriesList>>, TError = NotFoundError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategoriesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesList>>> = ({ signal }) => categoriesList({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CategoriesListQueryResult = NonNullable<Awaited<ReturnType<typeof categoriesList>>>
export type CategoriesListQueryError = NotFoundError


export function useCategoriesList<TData = Awaited<ReturnType<typeof categoriesList>>, TError = NotFoundError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesList>>,
          TError,
          Awaited<ReturnType<typeof categoriesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategoriesList<TData = Awaited<ReturnType<typeof categoriesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesList>>,
          TError,
          Awaited<ReturnType<typeof categoriesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategoriesList<TData = Awaited<ReturnType<typeof categoriesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCategoriesList<TData = Awaited<ReturnType<typeof categoriesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCategoriesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type categoriesCreateResponse200 = {
  data: Category
  status: 200
}

export type categoriesCreateResponse400 = {
  data: ValidationError
  status: 400
}

export type categoriesCreateResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categoriesCreateResponseSuccess = (categoriesCreateResponse200) & {
  headers: Headers;
};
export type categoriesCreateResponseError = (categoriesCreateResponse400 | categoriesCreateResponse500) & {
  headers: Headers;
};

export type categoriesCreateResponse = (categoriesCreateResponseSuccess | categoriesCreateResponseError)

export const getCategoriesCreateUrl = () => {


  

  return `/api/v1/categories`
}

export const categoriesCreate = async (categoryCreate: CategoryCreate, options?: RequestInit): Promise<categoriesCreateResponse> => {
  
  const res = await fetch(getCategoriesCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      categoryCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categoriesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categoriesCreateResponse
}




export const getCategoriesCreateMutationOptions = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesCreate>>, TError,{data: CategoryCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof categoriesCreate>>, TError,{data: CategoryCreate}, TContext> => {

const mutationKey = ['categoriesCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categoriesCreate>>, {data: CategoryCreate}> = (props) => {
          const {data} = props ?? {};

          return  categoriesCreate(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategoriesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof categoriesCreate>>>
    export type CategoriesCreateMutationBody = CategoryCreate
    export type CategoriesCreateMutationError = ValidationError | InternalServerError

    export const useCategoriesCreate = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesCreate>>, TError,{data: CategoryCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof categoriesCreate>>,
        TError,
        {data: CategoryCreate},
        TContext
      > => {

      const mutationOptions = getCategoriesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type categoriesGetResponse200 = {
  data: Category
  status: 200
}

export type categoriesGetResponse404 = {
  data: NotFoundError
  status: 404
}

export type categoriesGetResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categoriesGetResponseSuccess = (categoriesGetResponse200) & {
  headers: Headers;
};
export type categoriesGetResponseError = (categoriesGetResponse404 | categoriesGetResponse500) & {
  headers: Headers;
};

export type categoriesGetResponse = (categoriesGetResponseSuccess | categoriesGetResponseError)

export const getCategoriesGetUrl = (categoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}`
}

export const categoriesGet = async (categoryId: number, options?: RequestInit): Promise<categoriesGetResponse> => {
  
  const res = await fetch(getCategoriesGetUrl(categoryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categoriesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categoriesGetResponse
}





export const getCategoriesGetQueryKey = (categoryId?: number,) => {
    return [
    `/api/v1/categories/${categoryId}`
    ] as const;
    }

    
export const getCategoriesGetQueryOptions = <TData = Awaited<ReturnType<typeof categoriesGet>>, TError = NotFoundError | InternalServerError>(categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategoriesGetQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesGet>>> = ({ signal }) => categoriesGet(categoryId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CategoriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof categoriesGet>>>
export type CategoriesGetQueryError = NotFoundError | InternalServerError


export function useCategoriesGet<TData = Awaited<ReturnType<typeof categoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categoriesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategoriesGet<TData = Awaited<ReturnType<typeof categoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categoriesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategoriesGet<TData = Awaited<ReturnType<typeof categoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCategoriesGet<TData = Awaited<ReturnType<typeof categoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCategoriesGetQueryOptions(categoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type categoriesDeleteResponse204 = {
  data: void
  status: 204
}

export type categoriesDeleteResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categoriesDeleteResponseSuccess = (categoriesDeleteResponse204) & {
  headers: Headers;
};
export type categoriesDeleteResponseError = (categoriesDeleteResponse500) & {
  headers: Headers;
};

export type categoriesDeleteResponse = (categoriesDeleteResponseSuccess | categoriesDeleteResponseError)

export const getCategoriesDeleteUrl = (categoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}`
}

export const categoriesDelete = async (categoryId: number, options?: RequestInit): Promise<categoriesDeleteResponse> => {
  
  const res = await fetch(getCategoriesDeleteUrl(categoryId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categoriesDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categoriesDeleteResponse
}




export const getCategoriesDeleteMutationOptions = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesDelete>>, TError,{categoryId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof categoriesDelete>>, TError,{categoryId: number}, TContext> => {

const mutationKey = ['categoriesDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categoriesDelete>>, {categoryId: number}> = (props) => {
          const {categoryId} = props ?? {};

          return  categoriesDelete(categoryId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategoriesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof categoriesDelete>>>
    
    export type CategoriesDeleteMutationError = InternalServerError

    export const useCategoriesDelete = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesDelete>>, TError,{categoryId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof categoriesDelete>>,
        TError,
        {categoryId: number},
        TContext
      > => {

      const mutationOptions = getCategoriesDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    