/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const categoriesListResponseItem = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  name: zod.string().min(1),
});
export const categoriesListResponse = zod.array(categoriesListResponseItem);

export const categoriesCreateBody = zod.object({
  name: zod.string().min(1),
});

export const categoriesCreateResponse = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  name: zod.string().min(1),
});

export const categoriesGetParams = zod.object({
  categoryId: zod.number(),
});

export const categoriesGetResponse = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  name: zod.string().min(1),
});

export const categoriesDeleteParams = zod.object({
  categoryId: zod.number(),
});
