/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface AccountInfoDTO {
  /** @minimum 1 */
  id: number;
  isOwner: boolean;
  name: string;
}
