/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { AuthClientEventNameDTO } from "./authClientEventNameDTO";

export interface AuthClientEventDTO {
  attemptId?: string;
  buildVersion: string;
  displayMode: string;
  event: AuthClientEventNameDTO;
  online: boolean;
}
