/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type AuthClientEventNameDTO =
  | "page_loaded"
  | "widget_script_loaded"
  | "widget_script_failed"
  | "auth_callback"
  | "login_started"
  | "login_succeeded"
  | "login_failed"
  | "session_confirmed";
