/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { CategoryDTOType } from "./categoryDTOType";

export interface CategoryDTO {
  /** @minimum 1 */
  accountId: number;
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  name: string;
  type: CategoryDTOType;
}
