/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { CategoryCreateDTOType } from "./categoryCreateDTOType";

export interface CategoryCreateDTO {
  /** @minLength 1 */
  name: string;
  type: CategoryCreateDTOType;
}
