/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface CategoryExpenseSummaryDTO {
  amount: number;
  /** @minimum 1 */
  categoryId: number;
  categoryName: string;
  changePercent: number | null;
  percentage: number;
  previousAmount: number;
  /** @minimum 0 */
  transactionCount: number;
}
