/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { CategoriesListType } from "./categoriesListType";

export type CategoriesListParams = {
  type?: CategoriesListType;
};
