/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { CategoryTransactionSummaryDTO } from "./categoryTransactionSummaryDTO";

export interface CategorySummaryDTO {
  categories: CategoryTransactionSummaryDTO[];
  changePercent: number | null;
  previousTotalAmount: number;
  totalAmount: number;
  /** @minimum 0 */
  transactionCount: number;
}
