/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ConflictErrorDTOStatusCode =
  (typeof ConflictErrorDTOStatusCode)[keyof typeof ConflictErrorDTOStatusCode];

export const ConflictErrorDTOStatusCode = {
  NUMBER_409: 409,
} as const;
