/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { ConflictErrorDTOCode } from "./conflictErrorDTOCode";
import type { ConflictErrorDTOStatusCode } from "./conflictErrorDTOStatusCode";

export interface ConflictErrorDTO {
  code: ConflictErrorDTOCode;
  message: string;
  statusCode: ConflictErrorDTOStatusCode;
}
