/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ForbiddenErrorDTOStatusCode =
  (typeof ForbiddenErrorDTOStatusCode)[keyof typeof ForbiddenErrorDTOStatusCode];

export const ForbiddenErrorDTOStatusCode = {
  NUMBER_403: 403,
} as const;
