/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { ForbiddenErrorDTOCode } from "./forbiddenErrorDTOCode";
import type { ForbiddenErrorDTOStatusCode } from "./forbiddenErrorDTOStatusCode";

export interface ForbiddenErrorDTO {
  code: ForbiddenErrorDTOCode;
  message: string;
  statusCode: ForbiddenErrorDTOStatusCode;
}
