/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ForbiddenErrorDTOCode =
  (typeof ForbiddenErrorDTOCode)[keyof typeof ForbiddenErrorDTOCode];

export const ForbiddenErrorDTOCode = {
  FORBIDDEN: "FORBIDDEN",
} as const;
