/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type InternalServerErrorDTOStatusCode =
  (typeof InternalServerErrorDTOStatusCode)[keyof typeof InternalServerErrorDTOStatusCode];

 
export const InternalServerErrorDTOStatusCode = {
  NUMBER_500: 500,
} as const;
