/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type InternalServerErrorDTOCode =
  (typeof InternalServerErrorDTOCode)[keyof typeof InternalServerErrorDTOCode];

 
export const InternalServerErrorDTOCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
