/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type InvitationNotFoundErrorDTOStatusCode =
  (typeof InvitationNotFoundErrorDTOStatusCode)[keyof typeof InvitationNotFoundErrorDTOStatusCode];

export const InvitationNotFoundErrorDTOStatusCode = {
  NUMBER_404: 404,
} as const;
