/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type InvitationNotFoundErrorDTOCode =
  (typeof InvitationNotFoundErrorDTOCode)[keyof typeof InvitationNotFoundErrorDTOCode];

export const InvitationNotFoundErrorDTOCode = {
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
} as const;
