/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type InvitationNotFoundErrorDTOCode =
  (typeof InvitationNotFoundErrorDTOCode)[keyof typeof InvitationNotFoundErrorDTOCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvitationNotFoundErrorDTOCode = {
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
} as const;
