/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { NoAccountErrorDTOCode } from "./noAccountErrorDTOCode";
import type { NoAccountErrorDTOStatusCode } from "./noAccountErrorDTOStatusCode";

export interface NoAccountErrorDTO {
  code: NoAccountErrorDTOCode;
  message: string;
  statusCode: NoAccountErrorDTOStatusCode;
}
