/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NoAccountErrorDTOStatusCode =
  (typeof NoAccountErrorDTOStatusCode)[keyof typeof NoAccountErrorDTOStatusCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoAccountErrorDTOStatusCode = {
  NUMBER_409: 409,
} as const;
