/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NoAccountErrorDTOStatusCode =
  (typeof NoAccountErrorDTOStatusCode)[keyof typeof NoAccountErrorDTOStatusCode];

export const NoAccountErrorDTOStatusCode = {
  NUMBER_409: 409,
} as const;
