/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { NotFoundErrorDTOCode } from "./notFoundErrorDTOCode";
import type { NotFoundErrorDTOStatusCode } from "./notFoundErrorDTOStatusCode";

export interface NotFoundErrorDTO {
  code: NotFoundErrorDTOCode;
  message: string;
  statusCode: NotFoundErrorDTOStatusCode;
}
