/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NotFoundErrorDTOStatusCode =
  (typeof NotFoundErrorDTOStatusCode)[keyof typeof NotFoundErrorDTOStatusCode];

export const NotFoundErrorDTOStatusCode = {
  NUMBER_404: 404,
} as const;
