/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface SubcategoryCreateDTO {
  /** @minimum 1 */
  categoryId: number;
  /** @minLength 1 */
  name: string;
}
