/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface TransactionSummaryDTO {
  expenseTotal: number;
  incomeTotal: number;
  periodBalance: number;
  totalBalance: number;
}
