/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { TransactionCreateDTOType } from "./transactionCreateDTOType";

export interface TransactionCreateDTO {
  /** @minimum 0.01 */
  amount: number;
  /** @minimum 1 */
  categoryId: number;
  date?: string;
  description?: string;
  type: TransactionCreateDTOType;
}
