/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { TransactionsCategorySummaryType } from "./transactionsCategorySummaryType";

export type TransactionsCategorySummaryParams = {
  from: string;
  to: string;
  compareFrom: string;
  compareTo: string;
  type?: TransactionsCategorySummaryType;
};
