/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { UnauthorizedErrorDTOCode } from "./unauthorizedErrorDTOCode";
import type { UnauthorizedErrorDTOStatusCode } from "./unauthorizedErrorDTOStatusCode";

export interface UnauthorizedErrorDTO {
  code: (typeof UnauthorizedErrorDTOCode)[keyof typeof UnauthorizedErrorDTOCode];
  message: string;
  statusCode: UnauthorizedErrorDTOStatusCode;
}
