/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { UnauthorizedErrorDTOStatusCode } from "./unauthorizedErrorDTOStatusCode";

export interface UnauthorizedErrorDTO {
  code: "UNAUTHORIZED" | "INVALID_TOKEN" | "MISSING_TOKEN";
  message: string;
  statusCode: UnauthorizedErrorDTOStatusCode;
}
