/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type UnauthorizedErrorDTOStatusCode =
  (typeof UnauthorizedErrorDTOStatusCode)[keyof typeof UnauthorizedErrorDTOStatusCode];

export const UnauthorizedErrorDTOStatusCode = {
  NUMBER_401: 401,
} as const;
