/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { AccountInfoDTO } from "./accountInfoDTO";

export interface UserInfoDTO {
  accounts: AccountInfoDTO[];
  /** @minimum 1 */
  currentAccountId: number;
  /** @minimum 1 */
  userId: number;
}
