/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ValidationErrorDTOStatusCode =
  (typeof ValidationErrorDTOStatusCode)[keyof typeof ValidationErrorDTOStatusCode];

export const ValidationErrorDTOStatusCode = {
  NUMBER_400: 400,
} as const;
