/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ValidationErrorDTOCode =
  (typeof ValidationErrorDTOCode)[keyof typeof ValidationErrorDTOCode];

 
export const ValidationErrorDTOCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;
