/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface Category {
  /** @minimum 1 */
  id: number;
  /** @minimum 1 */
  userId: number;
  /** @minLength 1 */
  name: string;
}
