/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ValidationErrorCode = typeof ValidationErrorCode[keyof typeof ValidationErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
