/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CategoryCreateDTO,
  CategoryDTO,
  InternalServerErrorDTO,
  NotFoundErrorDTO,
  ValidationErrorDTO,
} from "../model";

import { fetcher } from "../../fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCategoriesListUrl = () => {
  return `/api/v1/categories`;
};

export const categoriesList = async (
  options?: RequestInit,
): Promise<CategoryDTO[]> => {
  return fetcher<CategoryDTO[]>(getCategoriesListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getCategoriesListQueryKey = () => {
  return ["categoriesList"] as const;
};

export const getCategoriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof categoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCategoriesListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesList>>> = ({
    signal,
  }) => categoriesList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof categoriesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CategoriesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof categoriesList>>
>;
export type CategoriesListQueryError =
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useCategoriesList<
  TData = Awaited<ReturnType<typeof categoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesList>>,
          TError,
          Awaited<ReturnType<typeof categoriesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategoriesList<
  TData = Awaited<ReturnType<typeof categoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesList>>,
          TError,
          Awaited<ReturnType<typeof categoriesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategoriesList<
  TData = Awaited<ReturnType<typeof categoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCategoriesList<
  TData = Awaited<ReturnType<typeof categoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCategoriesListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateCategoriesList = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getCategoriesListQueryKey() },
    options,
  );

  return queryClient;
};

export const getCategoriesCreateUrl = () => {
  return `/api/v1/categories`;
};

export const categoriesCreate = async (
  categoryCreateDTO: CategoryCreateDTO,
  options?: RequestInit,
): Promise<CategoryDTO> => {
  return fetcher<CategoryDTO>(getCategoriesCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(categoryCreateDTO),
  });
};

export const getCategoriesCreateMutationOptions = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof categoriesCreate>>,
    TError,
    { data: CategoryCreateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof categoriesCreate>>,
  TError,
  { data: CategoryCreateDTO },
  TContext
> => {
  const mutationKey = ["categoriesCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof categoriesCreate>>,
    { data: CategoryCreateDTO }
  > = (props) => {
    const { data } = props ?? {};

    return categoriesCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CategoriesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof categoriesCreate>>
>;
export type CategoriesCreateMutationBody = CategoryCreateDTO;
export type CategoriesCreateMutationError =
  | ValidationErrorDTO
  | InternalServerErrorDTO;

export const useCategoriesCreate = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof categoriesCreate>>,
      TError,
      { data: CategoryCreateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof categoriesCreate>>,
  TError,
  { data: CategoryCreateDTO },
  TContext
> => {
  return useMutation(getCategoriesCreateMutationOptions(options), queryClient);
};
export const getCategoriesGetUrl = (categoryId: number) => {
  return `/api/v1/categories/${categoryId}`;
};

export const categoriesGet = async (
  categoryId: number,
  options?: RequestInit,
): Promise<CategoryDTO> => {
  return fetcher<CategoryDTO>(getCategoriesGetUrl(categoryId), {
    ...options,
    method: "GET",
  });
};

export const getCategoriesGetQueryKey = (categoryId: number) => {
  return ["categoriesGet", ...(categoryId ? [categoryId] : [])] as const;
};

export const getCategoriesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof categoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCategoriesGetQueryKey(categoryId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesGet>>> = ({
    signal,
  }) => categoriesGet(categoryId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!categoryId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof categoriesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CategoriesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof categoriesGet>>
>;
export type CategoriesGetQueryError = NotFoundErrorDTO | InternalServerErrorDTO;

export function useCategoriesGet<
  TData = Awaited<ReturnType<typeof categoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categoriesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategoriesGet<
  TData = Awaited<ReturnType<typeof categoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categoriesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategoriesGet<
  TData = Awaited<ReturnType<typeof categoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCategoriesGet<
  TData = Awaited<ReturnType<typeof categoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categoriesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCategoriesGetQueryOptions(categoryId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateCategoriesGet = async (
  queryClient: QueryClient,
  categoryId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getCategoriesGetQueryKey(categoryId) },
    options,
  );

  return queryClient;
};

export const getCategoriesDeleteUrl = (categoryId: number) => {
  return `/api/v1/categories/${categoryId}`;
};

export const categoriesDelete = async (
  categoryId: number,
  options?: RequestInit,
): Promise<void> => {
  return fetcher<void>(getCategoriesDeleteUrl(categoryId), {
    ...options,
    method: "DELETE",
  });
};

export const getCategoriesDeleteMutationOptions = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof categoriesDelete>>,
    TError,
    { categoryId: number },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof categoriesDelete>>,
  TError,
  { categoryId: number },
  TContext
> => {
  const mutationKey = ["categoriesDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof categoriesDelete>>,
    { categoryId: number }
  > = (props) => {
    const { categoryId } = props ?? {};

    return categoriesDelete(categoryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CategoriesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof categoriesDelete>>
>;

export type CategoriesDeleteMutationError = InternalServerErrorDTO;

export const useCategoriesDelete = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof categoriesDelete>>,
      TError,
      { categoryId: number },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof categoriesDelete>>,
  TError,
  { categoryId: number },
  TContext
> => {
  return useMutation(getCategoriesDeleteMutationOptions(options), queryClient);
};
