/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const CategoriesListQueryParams = zod.object({
  type: zod.enum(["income", "expense"]).optional(),
});

export const CategoriesListResponseItem = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  name: zod.string().min(1),
});
export const CategoriesListResponse = zod.array(CategoriesListResponseItem);

export const CategoriesCreateBody = zod.object({
  type: zod.enum(["income", "expense"]),
  name: zod.string().min(1),
});

export const CategoriesCreateResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  name: zod.string().min(1),
});

export const CategoriesGetParams = zod.object({
  categoryId: zod.number(),
});

export const CategoriesGetResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  name: zod.string().min(1),
});

export const CategoriesDeleteParams = zod.object({
  categoryId: zod.number(),
});
