/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const TransactionsListQueryParams = zod.object({
  from: zod.iso.datetime({}),
  to: zod.iso.datetime({}),
  type: zod.enum(["income", "expense"]).optional(),
});

export const transactionsListResponseAmountMin = 0.01;

export const TransactionsListResponseItem = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(transactionsListResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});
export const TransactionsListResponse = zod.array(TransactionsListResponseItem);

export const transactionsCreateBodyAmountMin = 0.01;

export const TransactionsCreateBody = zod.object({
  amount: zod.number().min(transactionsCreateBodyAmountMin),
  categoryId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.string().optional(),
  date: zod.iso.datetime({}).optional(),
});

export const transactionsCreateResponseAmountMin = 0.01;

export const TransactionsCreateResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(transactionsCreateResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const TransactionsSummaryQueryParams = zod.object({
  from: zod.iso.datetime({}),
  to: zod.iso.datetime({}),
});

export const TransactionsSummaryResponse = zod.object({
  initialBalance: zod.number(),
  incomeTotal: zod.number(),
  expenseTotal: zod.number(),
  periodBalance: zod.number(),
  totalBalance: zod.number(),
});

export const TransactionsGetParams = zod.object({
  transactionId: zod.number(),
});

export const transactionsGetResponseAmountMin = 0.01;

export const TransactionsGetResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(transactionsGetResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const TransactionsUpdateParams = zod.object({
  transactionId: zod.number(),
});

export const transactionsUpdateBodyAmountMin = 0.01;

export const TransactionsUpdateBody = zod.object({
  amount: zod.number().min(transactionsUpdateBodyAmountMin),
  categoryId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const transactionsUpdateResponseAmountMin = 0.01;

export const TransactionsUpdateResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(transactionsUpdateResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  type: zod.enum(["income", "expense"]),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const TransactionsDeleteParams = zod.object({
  transactionId: zod.number(),
});
