/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CategorySummaryDTO,
  InternalServerErrorDTO,
  NotFoundErrorDTO,
  TransactionCreateDTO,
  TransactionDTO,
  TransactionSummaryDTO,
  TransactionUpdateDTO,
  TransactionsCategorySummaryParams,
  TransactionsListParams,
  TransactionsSummaryParams,
  ValidationErrorDTO,
} from "../model";

import { fetcher } from "../../fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTransactionsListUrl = (params: TransactionsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/transactions?${stringifiedParams}`
    : `/api/v1/transactions`;
};

export const transactionsList = async (
  params: TransactionsListParams,
  options?: RequestInit,
): Promise<TransactionDTO[]> => {
  return fetcher<TransactionDTO[]>(getTransactionsListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getTransactionsListQueryKey = (
  params?: TransactionsListParams,
) => {
  return ["transactionsList", ...(params ? [params] : [])] as const;
};

export const getTransactionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof transactionsList>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTransactionsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof transactionsList>>
  > = ({ signal }) => transactionsList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof transactionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TransactionsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof transactionsList>>
>;
export type TransactionsListQueryError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useTransactionsList<
  TData = Awaited<ReturnType<typeof transactionsList>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsList>>,
          TError,
          Awaited<ReturnType<typeof transactionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsList<
  TData = Awaited<ReturnType<typeof transactionsList>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsList>>,
          TError,
          Awaited<ReturnType<typeof transactionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsList<
  TData = Awaited<ReturnType<typeof transactionsList>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTransactionsList<
  TData = Awaited<ReturnType<typeof transactionsList>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTransactionsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateTransactionsList = async (
  queryClient: QueryClient,
  params: TransactionsListParams,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getTransactionsListQueryKey(params) },
    options,
  );

  return queryClient;
};

export const getTransactionsCreateUrl = () => {
  return `/api/v1/transactions`;
};

export const transactionsCreate = async (
  transactionCreateDTO: TransactionCreateDTO,
  options?: RequestInit,
): Promise<TransactionDTO> => {
  return fetcher<TransactionDTO>(getTransactionsCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(transactionCreateDTO),
  });
};

export const getTransactionsCreateMutationOptions = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transactionsCreate>>,
    TError,
    { data: TransactionCreateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof transactionsCreate>>,
  TError,
  { data: TransactionCreateDTO },
  TContext
> => {
  const mutationKey = ["transactionsCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transactionsCreate>>,
    { data: TransactionCreateDTO }
  > = (props) => {
    const { data } = props ?? {};

    return transactionsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TransactionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof transactionsCreate>>
>;
export type TransactionsCreateMutationBody = TransactionCreateDTO;
export type TransactionsCreateMutationError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export const useTransactionsCreate = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transactionsCreate>>,
      TError,
      { data: TransactionCreateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof transactionsCreate>>,
  TError,
  { data: TransactionCreateDTO },
  TContext
> => {
  return useMutation(
    getTransactionsCreateMutationOptions(options),
    queryClient,
  );
};
export const getTransactionsCategorySummaryUrl = (
  params: TransactionsCategorySummaryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/transactions/category-summary?${stringifiedParams}`
    : `/api/v1/transactions/category-summary`;
};

export const transactionsCategorySummary = async (
  params: TransactionsCategorySummaryParams,
  options?: RequestInit,
): Promise<CategorySummaryDTO> => {
  return fetcher<CategorySummaryDTO>(
    getTransactionsCategorySummaryUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getTransactionsCategorySummaryQueryKey = (
  params?: TransactionsCategorySummaryParams,
) => {
  return ["transactionsCategorySummary", ...(params ? [params] : [])] as const;
};

export const getTransactionsCategorySummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof transactionsCategorySummary>>,
  TError = ValidationErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsCategorySummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsCategorySummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTransactionsCategorySummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof transactionsCategorySummary>>
  > = ({ signal }) =>
    transactionsCategorySummary(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof transactionsCategorySummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TransactionsCategorySummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof transactionsCategorySummary>>
>;
export type TransactionsCategorySummaryQueryError =
  | ValidationErrorDTO
  | InternalServerErrorDTO;

export function useTransactionsCategorySummary<
  TData = Awaited<ReturnType<typeof transactionsCategorySummary>>,
  TError = ValidationErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsCategorySummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsCategorySummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsCategorySummary>>,
          TError,
          Awaited<ReturnType<typeof transactionsCategorySummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsCategorySummary<
  TData = Awaited<ReturnType<typeof transactionsCategorySummary>>,
  TError = ValidationErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsCategorySummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsCategorySummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsCategorySummary>>,
          TError,
          Awaited<ReturnType<typeof transactionsCategorySummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsCategorySummary<
  TData = Awaited<ReturnType<typeof transactionsCategorySummary>>,
  TError = ValidationErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsCategorySummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsCategorySummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTransactionsCategorySummary<
  TData = Awaited<ReturnType<typeof transactionsCategorySummary>>,
  TError = ValidationErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsCategorySummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsCategorySummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTransactionsCategorySummaryQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateTransactionsCategorySummary = async (
  queryClient: QueryClient,
  params: TransactionsCategorySummaryParams,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getTransactionsCategorySummaryQueryKey(params) },
    options,
  );

  return queryClient;
};

export const getTransactionsSummaryUrl = (
  params: TransactionsSummaryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/transactions/summary?${stringifiedParams}`
    : `/api/v1/transactions/summary`;
};

export const transactionsSummary = async (
  params: TransactionsSummaryParams,
  options?: RequestInit,
): Promise<TransactionSummaryDTO> => {
  return fetcher<TransactionSummaryDTO>(getTransactionsSummaryUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getTransactionsSummaryQueryKey = (
  params?: TransactionsSummaryParams,
) => {
  return ["transactionsSummary", ...(params ? [params] : [])] as const;
};

export const getTransactionsSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof transactionsSummary>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTransactionsSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof transactionsSummary>>
  > = ({ signal }) =>
    transactionsSummary(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof transactionsSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TransactionsSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof transactionsSummary>>
>;
export type TransactionsSummaryQueryError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useTransactionsSummary<
  TData = Awaited<ReturnType<typeof transactionsSummary>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsSummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsSummary>>,
          TError,
          Awaited<ReturnType<typeof transactionsSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsSummary<
  TData = Awaited<ReturnType<typeof transactionsSummary>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsSummary>>,
          TError,
          Awaited<ReturnType<typeof transactionsSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsSummary<
  TData = Awaited<ReturnType<typeof transactionsSummary>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTransactionsSummary<
  TData = Awaited<ReturnType<typeof transactionsSummary>>,
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
>(
  params: TransactionsSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTransactionsSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateTransactionsSummary = async (
  queryClient: QueryClient,
  params: TransactionsSummaryParams,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getTransactionsSummaryQueryKey(params) },
    options,
  );

  return queryClient;
};

export const getTransactionsGetUrl = (transactionId: number) => {
  return `/api/v1/transactions/${transactionId}`;
};

export const transactionsGet = async (
  transactionId: number,
  options?: RequestInit,
): Promise<TransactionDTO> => {
  return fetcher<TransactionDTO>(getTransactionsGetUrl(transactionId), {
    ...options,
    method: "GET",
  });
};

export const getTransactionsGetQueryKey = (transactionId: number) => {
  return [
    "transactionsGet",
    ...(transactionId ? [transactionId] : []),
  ] as const;
};

export const getTransactionsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof transactionsGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  transactionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTransactionsGetQueryKey(transactionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof transactionsGet>>> = ({
    signal,
  }) => transactionsGet(transactionId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!transactionId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof transactionsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TransactionsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof transactionsGet>>
>;
export type TransactionsGetQueryError =
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useTransactionsGet<
  TData = Awaited<ReturnType<typeof transactionsGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  transactionId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsGet>>,
          TError,
          Awaited<ReturnType<typeof transactionsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsGet<
  TData = Awaited<ReturnType<typeof transactionsGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  transactionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transactionsGet>>,
          TError,
          Awaited<ReturnType<typeof transactionsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTransactionsGet<
  TData = Awaited<ReturnType<typeof transactionsGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  transactionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTransactionsGet<
  TData = Awaited<ReturnType<typeof transactionsGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  transactionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof transactionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTransactionsGetQueryOptions(transactionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateTransactionsGet = async (
  queryClient: QueryClient,
  transactionId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getTransactionsGetQueryKey(transactionId) },
    options,
  );

  return queryClient;
};

export const getTransactionsUpdateUrl = (transactionId: number) => {
  return `/api/v1/transactions/${transactionId}`;
};

export const transactionsUpdate = async (
  transactionId: number,
  transactionUpdateDTO: TransactionUpdateDTO,
  options?: RequestInit,
): Promise<TransactionDTO> => {
  return fetcher<TransactionDTO>(getTransactionsUpdateUrl(transactionId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(transactionUpdateDTO),
  });
};

export const getTransactionsUpdateMutationOptions = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transactionsUpdate>>,
    TError,
    { transactionId: number; data: TransactionUpdateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof transactionsUpdate>>,
  TError,
  { transactionId: number; data: TransactionUpdateDTO },
  TContext
> => {
  const mutationKey = ["transactionsUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transactionsUpdate>>,
    { transactionId: number; data: TransactionUpdateDTO }
  > = (props) => {
    const { transactionId, data } = props ?? {};

    return transactionsUpdate(transactionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TransactionsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof transactionsUpdate>>
>;
export type TransactionsUpdateMutationBody = TransactionUpdateDTO;
export type TransactionsUpdateMutationError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export const useTransactionsUpdate = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transactionsUpdate>>,
      TError,
      { transactionId: number; data: TransactionUpdateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof transactionsUpdate>>,
  TError,
  { transactionId: number; data: TransactionUpdateDTO },
  TContext
> => {
  return useMutation(
    getTransactionsUpdateMutationOptions(options),
    queryClient,
  );
};
export const getTransactionsDeleteUrl = (transactionId: number) => {
  return `/api/v1/transactions/${transactionId}`;
};

export const transactionsDelete = async (
  transactionId: number,
  options?: RequestInit,
): Promise<void> => {
  return fetcher<void>(getTransactionsDeleteUrl(transactionId), {
    ...options,
    method: "DELETE",
  });
};

export const getTransactionsDeleteMutationOptions = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transactionsDelete>>,
    TError,
    { transactionId: number },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof transactionsDelete>>,
  TError,
  { transactionId: number },
  TContext
> => {
  const mutationKey = ["transactionsDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transactionsDelete>>,
    { transactionId: number }
  > = (props) => {
    const { transactionId } = props ?? {};

    return transactionsDelete(transactionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TransactionsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof transactionsDelete>>
>;

export type TransactionsDeleteMutationError = InternalServerErrorDTO;

export const useTransactionsDelete = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transactionsDelete>>,
      TError,
      { transactionId: number },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof transactionsDelete>>,
  TError,
  { transactionId: number },
  TContext
> => {
  return useMutation(
    getTransactionsDeleteMutationOptions(options),
    queryClient,
  );
};
