/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as PublicRouteRouteImport } from './_public/route'
import { Route as PrivateRouteRouteImport } from './_private/route'
import { Route as PrivateIndexRouteImport } from './_private/index'
import { Route as PublicLoginRouteImport } from './_public/login'
import { Route as PrivateSettingsRouteImport } from './_private/settings'
import { Route as PrivateDashboardRouteImport } from './_private/dashboard'
import { Route as PrivateCategoriesRouteImport } from './_private/categories'
import { Route as PublicInviteCodeRouteImport } from './_public/invite.$code'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCategoriesRoute = PrivateCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicInviteCodeRoute = PublicInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/categories': typeof PrivateCategoriesRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/settings': typeof PrivateSettingsRoute
  '/login': typeof PublicLoginRoute
  '/invite/$code': typeof PublicInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/categories': typeof PrivateCategoriesRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/settings': typeof PrivateSettingsRoute
  '/login': typeof PublicLoginRoute
  '/invite/$code': typeof PublicInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/categories': typeof PrivateCategoriesRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_private/': typeof PrivateIndexRoute
  '/_public/invite/$code': typeof PublicInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/invite/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/invite/$code'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/categories'
    | '/_private/dashboard'
    | '/_private/settings'
    | '/_public/login'
    | '/_private/'
    | '/_public/invite/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/categories': {
      id: '/_private/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/invite/$code': {
      id: '/_public/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof PublicInviteCodeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateCategoriesRoute: typeof PrivateCategoriesRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateCategoriesRoute: PrivateCategoriesRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicInviteCodeRoute: typeof PublicInviteCodeRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicInviteCodeRoute: PublicInviteCodeRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
