/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const AccountsListResponseItem = zod.object({
  id: zod.number().min(1),
  name: zod.string().min(1),
  ownerId: zod.number().min(1),
  createdAt: zod.iso.datetime({}),
});
export const AccountsListResponse = zod.array(AccountsListResponseItem);

export const AccountsRedeemInvitationBody = zod.object({
  code: zod.string(),
});

export const AccountsRedeemInvitationResponse = zod.object({
  id: zod.number().min(1),
  code: zod.string(),
  accountId: zod.number().min(1),
  expiresAt: zod.iso.datetime({}),
  usedAt: zod.iso.datetime({}).optional(),
  usedBy: zod.number().min(1).optional(),
});

export const AccountsUpdateParams = zod.object({
  accountId: zod.number().min(1),
});

export const AccountsUpdateBody = zod.object({
  name: zod.string().min(1).optional(),
});

export const AccountsUpdateResponse = zod.object({
  id: zod.number().min(1),
  name: zod.string().min(1),
  ownerId: zod.number().min(1),
  createdAt: zod.iso.datetime({}),
});

export const AccountsCreateInvitationParams = zod.object({
  accountId: zod.number(),
});

export const AccountsCreateInvitationResponse = zod.object({
  id: zod.number().min(1),
  code: zod.string(),
  accountId: zod.number().min(1),
  expiresAt: zod.iso.datetime({}),
  usedAt: zod.iso.datetime({}).optional(),
  usedBy: zod.number().min(1).optional(),
});

export const AccountsListMembersParams = zod.object({
  accountId: zod.number(),
});

export const AccountsListMembersResponseItem = zod.object({
  userId: zod.number().min(1),
  firstName: zod.union([zod.string(), zod.null()]).optional(),
  photoUrl: zod.union([zod.string(), zod.null()]).optional(),
});
export const AccountsListMembersResponse = zod.array(
  AccountsListMembersResponseItem,
);
