/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface AccountDTO {
  createdAt: string;
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  ownerId: number;
}
