/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { AccountUpdateMergePatchUpdateDTOName } from "./accountUpdateMergePatchUpdateDTOName";

export interface AccountUpdateMergePatchUpdateDTO {
  /** @minLength 1 */
  name?: AccountUpdateMergePatchUpdateDTOName;
}
