/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { ExpenseDTODescription } from "./expenseDTODescription";

export interface ExpenseDTO {
  /** @minimum 1 */
  accountId: number;
  /** @minimum 0.01 */
  amount: number;
  /** @minimum 1 */
  categoryId: number;
  date: string;
  description?: ExpenseDTODescription;
  /** @minimum 1 */
  id: number;
}
