/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ForbiddenErrorDTOStatusCode =
  (typeof ForbiddenErrorDTOStatusCode)[keyof typeof ForbiddenErrorDTOStatusCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ForbiddenErrorDTOStatusCode = {
  NUMBER_403: 403,
} as const;
