/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { InvitationNotFoundErrorDTOCode } from "./invitationNotFoundErrorDTOCode";
import type { InvitationNotFoundErrorDTOStatusCode } from "./invitationNotFoundErrorDTOStatusCode";

export interface InvitationNotFoundErrorDTO {
  code: InvitationNotFoundErrorDTOCode;
  message: string;
  statusCode: InvitationNotFoundErrorDTOStatusCode;
}
