/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NotFoundErrorDTOCode =
  (typeof NotFoundErrorDTOCode)[keyof typeof NotFoundErrorDTOCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorDTOCode = {
  NOT_FOUND: "NOT_FOUND",
} as const;
