/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NotFoundErrorDTOStatusCode =
  (typeof NotFoundErrorDTOStatusCode)[keyof typeof NotFoundErrorDTOStatusCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorDTOStatusCode = {
  NUMBER_404: 404,
} as const;
