/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type ValidationErrorDTOStatusCode =
  (typeof ValidationErrorDTOStatusCode)[keyof typeof ValidationErrorDTOStatusCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorDTOStatusCode = {
  NUMBER_400: 400,
} as const;
