/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { ValidationErrorDTOCode } from "./validationErrorDTOCode";
import type { ValidationErrorDTOStatusCode } from "./validationErrorDTOStatusCode";

export interface ValidationErrorDTO {
  code: ValidationErrorDTOCode;
  message: string;
  statusCode: ValidationErrorDTOStatusCode;
}
