/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const AuthClientEventBody = zod.object({
  event: zod.enum([
    "page_loaded",
    "widget_script_loaded",
    "widget_script_failed",
    "auth_callback",
    "login_started",
    "login_succeeded",
    "login_failed",
    "session_confirmed",
  ]),
  buildVersion: zod.string(),
  attemptId: zod.string().optional(),
  displayMode: zod.string(),
  online: zod.boolean(),
});

export const AuthClientEventResponse = zod.object({
  success: zod.boolean(),
});

export const AuthLoginBody = zod.object({
  id: zod.number().min(1),
  first_name: zod.string(),
  last_name: zod.string().optional(),
  username: zod.string().optional(),
  photo_url: zod.string().optional(),
  auth_date: zod.number().min(1),
  hash: zod.string(),
});

export const AuthLoginResponse = zod.object({
  success: zod.boolean(),
});

export const AuthLogoutResponse = zod.object({
  success: zod.boolean(),
});

export const AuthMeResponse = zod.object({
  userId: zod.number().min(1),
  currentAccountId: zod.number().min(1),
  accounts: zod.array(
    zod.object({
      id: zod.number().min(1),
      name: zod.string(),
      initialBalance: zod.number(),
      isOwner: zod.boolean(),
    }),
  ),
});

export const AuthRefreshResponse = zod.object({
  success: zod.boolean(),
});

export const AuthSwitchAccountBody = zod.object({
  accountId: zod.number().min(1),
});

export const AuthSwitchAccountResponse = zod.object({
  success: zod.boolean(),
});
