/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthClientEventDTO,
  ForbiddenErrorDTO,
  InternalServerErrorDTO,
  LoginRequestDTO,
  NoAccountErrorDTO,
  SuccessResponseDTO,
  SwitchAccountRequestDTO,
  UnauthorizedErrorDTO,
  UserInfoDTO,
} from "../model";

import { fetcher } from "../../fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthClientEventUrl = () => {
  return `/api/v1/auth/client-event`;
};

export const authClientEvent = async (
  authClientEventDTO: AuthClientEventDTO,
  options?: RequestInit,
): Promise<SuccessResponseDTO> => {
  return fetcher<SuccessResponseDTO>(getAuthClientEventUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authClientEventDTO),
  });
};

export const getAuthClientEventMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authClientEvent>>,
    TError,
    { data: AuthClientEventDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authClientEvent>>,
  TError,
  { data: AuthClientEventDTO },
  TContext
> => {
  const mutationKey = ["authClientEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authClientEvent>>,
    { data: AuthClientEventDTO }
  > = (props) => {
    const { data } = props ?? {};

    return authClientEvent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthClientEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof authClientEvent>>
>;
export type AuthClientEventMutationBody = AuthClientEventDTO;
export type AuthClientEventMutationError = unknown;

export const useAuthClientEvent = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authClientEvent>>,
      TError,
      { data: AuthClientEventDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authClientEvent>>,
  TError,
  { data: AuthClientEventDTO },
  TContext
> => {
  return useMutation(getAuthClientEventMutationOptions(options), queryClient);
};
export const getAuthLoginUrl = () => {
  return `/api/v1/auth/login`;
};

export const authLogin = async (
  loginRequestDTO: LoginRequestDTO,
  options?: RequestInit,
): Promise<SuccessResponseDTO> => {
  return fetcher<SuccessResponseDTO>(getAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequestDTO),
  });
};

export const getAuthLoginMutationOptions = <
  TError =
    | UnauthorizedErrorDTO
    | void
    | NoAccountErrorDTO
    | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    { data: LoginRequestDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: LoginRequestDTO },
  TContext
> => {
  const mutationKey = ["authLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogin>>,
    { data: LoginRequestDTO }
  > = (props) => {
    const { data } = props ?? {};

    return authLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogin>>
>;
export type AuthLoginMutationBody = LoginRequestDTO;
export type AuthLoginMutationError =
  | UnauthorizedErrorDTO
  | void
  | NoAccountErrorDTO
  | InternalServerErrorDTO;

export const useAuthLogin = <
  TError =
    | UnauthorizedErrorDTO
    | void
    | NoAccountErrorDTO
    | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogin>>,
      TError,
      { data: LoginRequestDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: LoginRequestDTO },
  TContext
> => {
  return useMutation(getAuthLoginMutationOptions(options), queryClient);
};
export const getAuthLogoutUrl = () => {
  return `/api/v1/auth/logout`;
};

export const authLogout = async (
  options?: RequestInit,
): Promise<SuccessResponseDTO> => {
  return fetcher<SuccessResponseDTO>(getAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getAuthLogoutMutationOptions = <
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogout>>,
    void
  > = () => {
    return authLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>;

export type AuthLogoutMutationError =
  | UnauthorizedErrorDTO
  | InternalServerErrorDTO;

export const useAuthLogout = <
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getAuthLogoutMutationOptions(options), queryClient);
};
export const getAuthMeUrl = () => {
  return `/api/v1/auth/me`;
};

export const authMe = async (options?: RequestInit): Promise<UserInfoDTO> => {
  return fetcher<UserInfoDTO>(getAuthMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAuthMeQueryKey = () => {
  return ["authMe"] as const;
};

export const getAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({
    signal,
  }) => authMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>;
export type AuthMeQueryError = UnauthorizedErrorDTO | InternalServerErrorDTO;

export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateAuthMe = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getAuthMeQueryKey() },
    options,
  );

  return queryClient;
};

export const getAuthRefreshUrl = () => {
  return `/api/v1/auth/refresh`;
};

export const authRefresh = async (
  options?: RequestInit,
): Promise<SuccessResponseDTO> => {
  return fetcher<SuccessResponseDTO>(getAuthRefreshUrl(), {
    ...options,
    method: "POST",
  });
};

export const getAuthRefreshMutationOptions = <
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRefresh>>,
    void
  > = () => {
    return authRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRefresh>>
>;

export type AuthRefreshMutationError =
  | UnauthorizedErrorDTO
  | InternalServerErrorDTO;

export const useAuthRefresh = <
  TError = UnauthorizedErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRefresh>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRefresh>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getAuthRefreshMutationOptions(options), queryClient);
};
export const getAuthSwitchAccountUrl = () => {
  return `/api/v1/auth/switch-account`;
};

export const authSwitchAccount = async (
  switchAccountRequestDTO: SwitchAccountRequestDTO,
  options?: RequestInit,
): Promise<SuccessResponseDTO> => {
  return fetcher<SuccessResponseDTO>(getAuthSwitchAccountUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(switchAccountRequestDTO),
  });
};

export const getAuthSwitchAccountMutationOptions = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authSwitchAccount>>,
    TError,
    { data: SwitchAccountRequestDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authSwitchAccount>>,
  TError,
  { data: SwitchAccountRequestDTO },
  TContext
> => {
  const mutationKey = ["authSwitchAccount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authSwitchAccount>>,
    { data: SwitchAccountRequestDTO }
  > = (props) => {
    const { data } = props ?? {};

    return authSwitchAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthSwitchAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof authSwitchAccount>>
>;
export type AuthSwitchAccountMutationBody = SwitchAccountRequestDTO;
export type AuthSwitchAccountMutationError =
  | UnauthorizedErrorDTO
  | ForbiddenErrorDTO
  | InternalServerErrorDTO;

export const useAuthSwitchAccount = <
  TError = UnauthorizedErrorDTO | ForbiddenErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authSwitchAccount>>,
      TError,
      { data: SwitchAccountRequestDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authSwitchAccount>>,
  TError,
  { data: SwitchAccountRequestDTO },
  TContext
> => {
  return useMutation(getAuthSwitchAccountMutationOptions(options), queryClient);
};
