/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalServerError,
  NotFoundError,
  Subcategory,
  SubcategoryCreate,
  ValidationError
} from '.././model';





export type categorySubcategoriesListResponse200 = {
  data: Subcategory[]
  status: 200
}

export type categorySubcategoriesListResponse404 = {
  data: NotFoundError
  status: 404
}

export type categorySubcategoriesListResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categorySubcategoriesListResponseSuccess = (categorySubcategoriesListResponse200) & {
  headers: Headers;
};
export type categorySubcategoriesListResponseError = (categorySubcategoriesListResponse404 | categorySubcategoriesListResponse500) & {
  headers: Headers;
};

export type categorySubcategoriesListResponse = (categorySubcategoriesListResponseSuccess | categorySubcategoriesListResponseError)

export const getCategorySubcategoriesListUrl = (categoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}/subcategories`
}

export const categorySubcategoriesList = async (categoryId: number, options?: RequestInit): Promise<categorySubcategoriesListResponse> => {
  
  const res = await fetch(getCategorySubcategoriesListUrl(categoryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categorySubcategoriesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categorySubcategoriesListResponse
}





export const getCategorySubcategoriesListQueryKey = (categoryId?: number,) => {
    return [
    `/api/v1/categories/${categoryId}/subcategories`
    ] as const;
    }

    
export const getCategorySubcategoriesListQueryOptions = <TData = Awaited<ReturnType<typeof categorySubcategoriesList>>, TError = NotFoundError | InternalServerError>(categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategorySubcategoriesListQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categorySubcategoriesList>>> = ({ signal }) => categorySubcategoriesList(categoryId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CategorySubcategoriesListQueryResult = NonNullable<Awaited<ReturnType<typeof categorySubcategoriesList>>>
export type CategorySubcategoriesListQueryError = NotFoundError | InternalServerError


export function useCategorySubcategoriesList<TData = Awaited<ReturnType<typeof categorySubcategoriesList>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesList>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategorySubcategoriesList<TData = Awaited<ReturnType<typeof categorySubcategoriesList>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesList>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategorySubcategoriesList<TData = Awaited<ReturnType<typeof categorySubcategoriesList>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCategorySubcategoriesList<TData = Awaited<ReturnType<typeof categorySubcategoriesList>>, TError = NotFoundError | InternalServerError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCategorySubcategoriesListQueryOptions(categoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type categorySubcategoriesCreateResponse201 = {
  data: Subcategory
  status: 201
}

export type categorySubcategoriesCreateResponse400 = {
  data: ValidationError
  status: 400
}

export type categorySubcategoriesCreateResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categorySubcategoriesCreateResponseSuccess = (categorySubcategoriesCreateResponse201) & {
  headers: Headers;
};
export type categorySubcategoriesCreateResponseError = (categorySubcategoriesCreateResponse400 | categorySubcategoriesCreateResponse500) & {
  headers: Headers;
};

export type categorySubcategoriesCreateResponse = (categorySubcategoriesCreateResponseSuccess | categorySubcategoriesCreateResponseError)

export const getCategorySubcategoriesCreateUrl = (categoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}/subcategories`
}

export const categorySubcategoriesCreate = async (categoryId: number,
    subcategoryCreate: SubcategoryCreate, options?: RequestInit): Promise<categorySubcategoriesCreateResponse> => {
  
  const res = await fetch(getCategorySubcategoriesCreateUrl(categoryId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subcategoryCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categorySubcategoriesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categorySubcategoriesCreateResponse
}




export const getCategorySubcategoriesCreateMutationOptions = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesCreate>>, TError,{categoryId: number;data: SubcategoryCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesCreate>>, TError,{categoryId: number;data: SubcategoryCreate}, TContext> => {

const mutationKey = ['categorySubcategoriesCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categorySubcategoriesCreate>>, {categoryId: number;data: SubcategoryCreate}> = (props) => {
          const {categoryId,data} = props ?? {};

          return  categorySubcategoriesCreate(categoryId,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategorySubcategoriesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof categorySubcategoriesCreate>>>
    export type CategorySubcategoriesCreateMutationBody = SubcategoryCreate
    export type CategorySubcategoriesCreateMutationError = ValidationError | InternalServerError

    export const useCategorySubcategoriesCreate = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesCreate>>, TError,{categoryId: number;data: SubcategoryCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
        TError,
        {categoryId: number;data: SubcategoryCreate},
        TContext
      > => {

      const mutationOptions = getCategorySubcategoriesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type categorySubcategoriesGetResponse200 = {
  data: Subcategory
  status: 200
}

export type categorySubcategoriesGetResponse404 = {
  data: NotFoundError
  status: 404
}

export type categorySubcategoriesGetResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categorySubcategoriesGetResponseSuccess = (categorySubcategoriesGetResponse200) & {
  headers: Headers;
};
export type categorySubcategoriesGetResponseError = (categorySubcategoriesGetResponse404 | categorySubcategoriesGetResponse500) & {
  headers: Headers;
};

export type categorySubcategoriesGetResponse = (categorySubcategoriesGetResponseSuccess | categorySubcategoriesGetResponseError)

export const getCategorySubcategoriesGetUrl = (categoryId: number,
    subcategoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}/subcategories/${subcategoryId}`
}

export const categorySubcategoriesGet = async (categoryId: number,
    subcategoryId: number, options?: RequestInit): Promise<categorySubcategoriesGetResponse> => {
  
  const res = await fetch(getCategorySubcategoriesGetUrl(categoryId,subcategoryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categorySubcategoriesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categorySubcategoriesGetResponse
}





export const getCategorySubcategoriesGetQueryKey = (categoryId?: number,
    subcategoryId?: number,) => {
    return [
    `/api/v1/categories/${categoryId}/subcategories/${subcategoryId}`
    ] as const;
    }

    
export const getCategorySubcategoriesGetQueryOptions = <TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError = NotFoundError | InternalServerError>(categoryId: number,
    subcategoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategorySubcategoriesGetQueryKey(categoryId,subcategoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categorySubcategoriesGet>>> = ({ signal }) => categorySubcategoriesGet(categoryId,subcategoryId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId && subcategoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CategorySubcategoriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof categorySubcategoriesGet>>>
export type CategorySubcategoriesGetQueryError = NotFoundError | InternalServerError


export function useCategorySubcategoriesGet<TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number,
    subcategoryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategorySubcategoriesGet<TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number,
    subcategoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCategorySubcategoriesGet<TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number,
    subcategoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCategorySubcategoriesGet<TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError = NotFoundError | InternalServerError>(
 categoryId: number,
    subcategoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categorySubcategoriesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCategorySubcategoriesGetQueryOptions(categoryId,subcategoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type categorySubcategoriesDeleteResponse204 = {
  data: void
  status: 204
}

export type categorySubcategoriesDeleteResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type categorySubcategoriesDeleteResponseSuccess = (categorySubcategoriesDeleteResponse204) & {
  headers: Headers;
};
export type categorySubcategoriesDeleteResponseError = (categorySubcategoriesDeleteResponse500) & {
  headers: Headers;
};

export type categorySubcategoriesDeleteResponse = (categorySubcategoriesDeleteResponseSuccess | categorySubcategoriesDeleteResponseError)

export const getCategorySubcategoriesDeleteUrl = (categoryId: number,
    subcategoryId: number,) => {


  

  return `/api/v1/categories/${categoryId}/subcategories/${subcategoryId}`
}

export const categorySubcategoriesDelete = async (categoryId: number,
    subcategoryId: number, options?: RequestInit): Promise<categorySubcategoriesDeleteResponse> => {
  
  const res = await fetch(getCategorySubcategoriesDeleteUrl(categoryId,subcategoryId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: categorySubcategoriesDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as categorySubcategoriesDeleteResponse
}




export const getCategorySubcategoriesDeleteMutationOptions = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesDelete>>, TError,{categoryId: number;subcategoryId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesDelete>>, TError,{categoryId: number;subcategoryId: number}, TContext> => {

const mutationKey = ['categorySubcategoriesDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categorySubcategoriesDelete>>, {categoryId: number;subcategoryId: number}> = (props) => {
          const {categoryId,subcategoryId} = props ?? {};

          return  categorySubcategoriesDelete(categoryId,subcategoryId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategorySubcategoriesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof categorySubcategoriesDelete>>>
    
    export type CategorySubcategoriesDeleteMutationError = InternalServerError

    export const useCategorySubcategoriesDelete = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categorySubcategoriesDelete>>, TError,{categoryId: number;subcategoryId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
        TError,
        {categoryId: number;subcategoryId: number},
        TContext
      > => {

      const mutationOptions = getCategorySubcategoriesDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    