/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  InternalServerErrorDTO,
  NotFoundErrorDTO,
  SubcategoryCreateDTO,
  SubcategoryDTO,
  ValidationErrorDTO,
} from ".././model";

export const getCategorySubcategoriesListUrl = (categoryId: number) => {
  return `/api/v1/categories/${categoryId}/subcategories`;
};

export const categorySubcategoriesList = async (
  categoryId: number,
  options?: RequestInit,
): Promise<SubcategoryDTO[]> => {
  const res = await fetch(getCategorySubcategoriesListUrl(categoryId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SubcategoryDTO[] = body ? JSON.parse(body) : {};
  return data;
};

export const getCategorySubcategoriesListQueryKey = (categoryId?: number) => {
  return ["categorySubcategoriesList"] as const;
};

export const getCategorySubcategoriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof categorySubcategoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesList>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCategorySubcategoriesListQueryKey(categoryId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof categorySubcategoriesList>>
  > = ({ signal }) =>
    categorySubcategoriesList(categoryId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!categoryId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof categorySubcategoriesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CategorySubcategoriesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof categorySubcategoriesList>>
>;
export type CategorySubcategoriesListQueryError =
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useCategorySubcategoriesList<
  TData = Awaited<ReturnType<typeof categorySubcategoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesList>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesList>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategorySubcategoriesList<
  TData = Awaited<ReturnType<typeof categorySubcategoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesList>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesList>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategorySubcategoriesList<
  TData = Awaited<ReturnType<typeof categorySubcategoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesList>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCategorySubcategoriesList<
  TData = Awaited<ReturnType<typeof categorySubcategoriesList>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesList>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCategorySubcategoriesListQueryOptions(
    categoryId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateCategorySubcategoriesList = async (
  queryClient: QueryClient,
  categoryId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getCategorySubcategoriesListQueryKey(categoryId) },
    options,
  );

  return queryClient;
};

export const getCategorySubcategoriesCreateUrl = (categoryId: number) => {
  return `/api/v1/categories/${categoryId}/subcategories`;
};

export const categorySubcategoriesCreate = async (
  categoryId: number,
  subcategoryCreateDTO: SubcategoryCreateDTO,
  options?: RequestInit,
): Promise<SubcategoryDTO> => {
  const res = await fetch(getCategorySubcategoriesCreateUrl(categoryId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(subcategoryCreateDTO),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SubcategoryDTO = body ? JSON.parse(body) : {};
  return data;
};

export const getCategorySubcategoriesCreateMutationOptions = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
    TError,
    { categoryId: number; data: SubcategoryCreateDTO },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
  TError,
  { categoryId: number; data: SubcategoryCreateDTO },
  TContext
> => {
  const mutationKey = ["categorySubcategoriesCreate"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
    { categoryId: number; data: SubcategoryCreateDTO }
  > = (props) => {
    const { categoryId, data } = props ?? {};

    return categorySubcategoriesCreate(categoryId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CategorySubcategoriesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof categorySubcategoriesCreate>>
>;
export type CategorySubcategoriesCreateMutationBody = SubcategoryCreateDTO;
export type CategorySubcategoriesCreateMutationError =
  | ValidationErrorDTO
  | InternalServerErrorDTO;

export const useCategorySubcategoriesCreate = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
      TError,
      { categoryId: number; data: SubcategoryCreateDTO },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof categorySubcategoriesCreate>>,
  TError,
  { categoryId: number; data: SubcategoryCreateDTO },
  TContext
> => {
  const mutationOptions =
    getCategorySubcategoriesCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getCategorySubcategoriesGetUrl = (
  categoryId: number,
  subcategoryId: number,
) => {
  return `/api/v1/categories/${categoryId}/subcategories/${subcategoryId}`;
};

export const categorySubcategoriesGet = async (
  categoryId: number,
  subcategoryId: number,
  options?: RequestInit,
): Promise<SubcategoryDTO> => {
  const res = await fetch(
    getCategorySubcategoriesGetUrl(categoryId, subcategoryId),
    {
      ...options,
      method: "GET",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SubcategoryDTO = body ? JSON.parse(body) : {};
  return data;
};

export const getCategorySubcategoriesGetQueryKey = (
  categoryId?: number,
  subcategoryId?: number,
) => {
  return ["categorySubcategoriesGet"] as const;
};

export const getCategorySubcategoriesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  subcategoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCategorySubcategoriesGetQueryKey(categoryId, subcategoryId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof categorySubcategoriesGet>>
  > = ({ signal }) =>
    categorySubcategoriesGet(categoryId, subcategoryId, {
      signal,
      ...fetchOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(categoryId && subcategoryId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof categorySubcategoriesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CategorySubcategoriesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof categorySubcategoriesGet>>
>;
export type CategorySubcategoriesGetQueryError =
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export function useCategorySubcategoriesGet<
  TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  subcategoryId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategorySubcategoriesGet<
  TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  subcategoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categorySubcategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof categorySubcategoriesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategorySubcategoriesGet<
  TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  subcategoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCategorySubcategoriesGet<
  TData = Awaited<ReturnType<typeof categorySubcategoriesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  categoryId: number,
  subcategoryId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof categorySubcategoriesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCategorySubcategoriesGetQueryOptions(
    categoryId,
    subcategoryId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateCategorySubcategoriesGet = async (
  queryClient: QueryClient,
  categoryId: number,
  subcategoryId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    {
      queryKey: getCategorySubcategoriesGetQueryKey(categoryId, subcategoryId),
    },
    options,
  );

  return queryClient;
};

export const getCategorySubcategoriesDeleteUrl = (
  categoryId: number,
  subcategoryId: number,
) => {
  return `/api/v1/categories/${categoryId}/subcategories/${subcategoryId}`;
};

export const categorySubcategoriesDelete = async (
  categoryId: number,
  subcategoryId: number,
  options?: RequestInit,
): Promise<void> => {
  const res = await fetch(
    getCategorySubcategoriesDeleteUrl(categoryId, subcategoryId),
    {
      ...options,
      method: "DELETE",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: void = body ? JSON.parse(body) : {};
  return data;
};

export const getCategorySubcategoriesDeleteMutationOptions = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
    TError,
    { categoryId: number; subcategoryId: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
  TError,
  { categoryId: number; subcategoryId: number },
  TContext
> => {
  const mutationKey = ["categorySubcategoriesDelete"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
    { categoryId: number; subcategoryId: number }
  > = (props) => {
    const { categoryId, subcategoryId } = props ?? {};

    return categorySubcategoriesDelete(categoryId, subcategoryId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CategorySubcategoriesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof categorySubcategoriesDelete>>
>;

export type CategorySubcategoriesDeleteMutationError = InternalServerErrorDTO;

export const useCategorySubcategoriesDelete = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
      TError,
      { categoryId: number; subcategoryId: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof categorySubcategoriesDelete>>,
  TError,
  { categoryId: number; subcategoryId: number },
  TContext
> => {
  const mutationOptions =
    getCategorySubcategoriesDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
