/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const categorySubcategoriesListParams = zod.object({
  categoryId: zod.number(),
});

export const categorySubcategoriesListResponseItem = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});
export const categorySubcategoriesListResponse = zod.array(
  categorySubcategoriesListResponseItem,
);

export const categorySubcategoriesCreateParams = zod.object({
  categoryId: zod.number(),
});

export const categorySubcategoriesCreateBody = zod.object({
  name: zod.string().min(1),
});

export const categorySubcategoriesGetParams = zod.object({
  categoryId: zod.number(),
  subcategoryId: zod.number(),
});

export const categorySubcategoriesGetResponse = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  categoryId: zod.number().min(1),
  name: zod.string().min(1),
});

export const categorySubcategoriesDeleteParams = zod.object({
  categoryId: zod.number(),
  subcategoryId: zod.number(),
});
