/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const expensesListResponseAmountMin = 0.01;

export const expensesListResponseItem = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  amount: zod.number().min(expensesListResponseAmountMin),
  categoryId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});
export const expensesListResponse = zod.array(expensesListResponseItem);

export const expensesCreateBodyAmountMin = 0.01;

export const expensesCreateBody = zod.object({
  amount: zod.number().min(expensesCreateBodyAmountMin),
  categoryId: zod.number().min(1),
  description: zod.string().optional(),
  date: zod.iso.datetime({}).optional(),
});

export const expensesCreateResponseAmountMin = 0.01;

export const expensesCreateResponse = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  amount: zod.number().min(expensesCreateResponseAmountMin),
  categoryId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const expensesGetParams = zod.object({
  expenseId: zod.number(),
});

export const expensesGetResponseAmountMin = 0.01;

export const expensesGetResponse = zod.object({
  id: zod.number().min(1),
  userId: zod.number().min(1),
  amount: zod.number().min(expensesGetResponseAmountMin),
  categoryId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const expensesDeleteParams = zod.object({
  expenseId: zod.number(),
});
