/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Expense,
  ExpenseCreate,
  InternalServerError,
  NotFoundError,
  ValidationError
} from '.././model';





export type expensesListResponse200 = {
  data: Expense[]
  status: 200
}

export type expensesListResponse404 = {
  data: NotFoundError
  status: 404
}
    
export type expensesListResponseSuccess = (expensesListResponse200) & {
  headers: Headers;
};
export type expensesListResponseError = (expensesListResponse404) & {
  headers: Headers;
};

export type expensesListResponse = (expensesListResponseSuccess | expensesListResponseError)

export const getExpensesListUrl = () => {


  

  return `/api/v1/expenses`
}

export const expensesList = async ( options?: RequestInit): Promise<expensesListResponse> => {
  
  const res = await fetch(getExpensesListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: expensesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as expensesListResponse
}





export const getExpensesListQueryKey = () => {
    return [
    `/api/v1/expenses`
    ] as const;
    }

    
export const getExpensesListQueryOptions = <TData = Awaited<ReturnType<typeof expensesList>>, TError = NotFoundError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExpensesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesList>>> = ({ signal }) => expensesList({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExpensesListQueryResult = NonNullable<Awaited<ReturnType<typeof expensesList>>>
export type ExpensesListQueryError = NotFoundError


export function useExpensesList<TData = Awaited<ReturnType<typeof expensesList>>, TError = NotFoundError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpensesList<TData = Awaited<ReturnType<typeof expensesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpensesList<TData = Awaited<ReturnType<typeof expensesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExpensesList<TData = Awaited<ReturnType<typeof expensesList>>, TError = NotFoundError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExpensesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type expensesCreateResponse200 = {
  data: Expense
  status: 200
}

export type expensesCreateResponse400 = {
  data: ValidationError
  status: 400
}

export type expensesCreateResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type expensesCreateResponseSuccess = (expensesCreateResponse200) & {
  headers: Headers;
};
export type expensesCreateResponseError = (expensesCreateResponse400 | expensesCreateResponse500) & {
  headers: Headers;
};

export type expensesCreateResponse = (expensesCreateResponseSuccess | expensesCreateResponseError)

export const getExpensesCreateUrl = () => {


  

  return `/api/v1/expenses`
}

export const expensesCreate = async (expenseCreate: ExpenseCreate, options?: RequestInit): Promise<expensesCreateResponse> => {
  
  const res = await fetch(getExpensesCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      expenseCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: expensesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as expensesCreateResponse
}




export const getExpensesCreateMutationOptions = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof expensesCreate>>, TError,{data: ExpenseCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof expensesCreate>>, TError,{data: ExpenseCreate}, TContext> => {

const mutationKey = ['expensesCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof expensesCreate>>, {data: ExpenseCreate}> = (props) => {
          const {data} = props ?? {};

          return  expensesCreate(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExpensesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof expensesCreate>>>
    export type ExpensesCreateMutationBody = ExpenseCreate
    export type ExpensesCreateMutationError = ValidationError | InternalServerError

    export const useExpensesCreate = <TError = ValidationError | InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof expensesCreate>>, TError,{data: ExpenseCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof expensesCreate>>,
        TError,
        {data: ExpenseCreate},
        TContext
      > => {

      const mutationOptions = getExpensesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type expensesGetResponse200 = {
  data: Expense
  status: 200
}

export type expensesGetResponse404 = {
  data: NotFoundError
  status: 404
}

export type expensesGetResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type expensesGetResponseSuccess = (expensesGetResponse200) & {
  headers: Headers;
};
export type expensesGetResponseError = (expensesGetResponse404 | expensesGetResponse500) & {
  headers: Headers;
};

export type expensesGetResponse = (expensesGetResponseSuccess | expensesGetResponseError)

export const getExpensesGetUrl = (expenseId: number,) => {


  

  return `/api/v1/expenses/${expenseId}`
}

export const expensesGet = async (expenseId: number, options?: RequestInit): Promise<expensesGetResponse> => {
  
  const res = await fetch(getExpensesGetUrl(expenseId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: expensesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as expensesGetResponse
}





export const getExpensesGetQueryKey = (expenseId?: number,) => {
    return [
    `/api/v1/expenses/${expenseId}`
    ] as const;
    }

    
export const getExpensesGetQueryOptions = <TData = Awaited<ReturnType<typeof expensesGet>>, TError = NotFoundError | InternalServerError>(expenseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExpensesGetQueryKey(expenseId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesGet>>> = ({ signal }) => expensesGet(expenseId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(expenseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExpensesGetQueryResult = NonNullable<Awaited<ReturnType<typeof expensesGet>>>
export type ExpensesGetQueryError = NotFoundError | InternalServerError


export function useExpensesGet<TData = Awaited<ReturnType<typeof expensesGet>>, TError = NotFoundError | InternalServerError>(
 expenseId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpensesGet<TData = Awaited<ReturnType<typeof expensesGet>>, TError = NotFoundError | InternalServerError>(
 expenseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpensesGet<TData = Awaited<ReturnType<typeof expensesGet>>, TError = NotFoundError | InternalServerError>(
 expenseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExpensesGet<TData = Awaited<ReturnType<typeof expensesGet>>, TError = NotFoundError | InternalServerError>(
 expenseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExpensesGetQueryOptions(expenseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type expensesDeleteResponse204 = {
  data: void
  status: 204
}

export type expensesDeleteResponse500 = {
  data: InternalServerError
  status: 500
}
    
export type expensesDeleteResponseSuccess = (expensesDeleteResponse204) & {
  headers: Headers;
};
export type expensesDeleteResponseError = (expensesDeleteResponse500) & {
  headers: Headers;
};

export type expensesDeleteResponse = (expensesDeleteResponseSuccess | expensesDeleteResponseError)

export const getExpensesDeleteUrl = (expenseId: number,) => {


  

  return `/api/v1/expenses/${expenseId}`
}

export const expensesDelete = async (expenseId: number, options?: RequestInit): Promise<expensesDeleteResponse> => {
  
  const res = await fetch(getExpensesDeleteUrl(expenseId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: expensesDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as expensesDeleteResponse
}




export const getExpensesDeleteMutationOptions = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof expensesDelete>>, TError,{expenseId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof expensesDelete>>, TError,{expenseId: number}, TContext> => {

const mutationKey = ['expensesDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof expensesDelete>>, {expenseId: number}> = (props) => {
          const {expenseId} = props ?? {};

          return  expensesDelete(expenseId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExpensesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof expensesDelete>>>
    
    export type ExpensesDeleteMutationError = InternalServerError

    export const useExpensesDelete = <TError = InternalServerError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof expensesDelete>>, TError,{expenseId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof expensesDelete>>,
        TError,
        {expenseId: number},
        TContext
      > => {

      const mutationOptions = getExpensesDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    