/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ExpenseCreateDTO,
  ExpenseDTO,
  InternalServerErrorDTO,
  NotFoundErrorDTO,
  ValidationErrorDTO,
} from ".././model";

export const getExpensesListUrl = () => {
  return `/api/v1/expenses`;
};

export const expensesList = async (
  options?: RequestInit,
): Promise<ExpenseDTO[]> => {
  const res = await fetch(getExpensesListUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ExpenseDTO[] = body ? JSON.parse(body) : {};
  return data;
};

export const getExpensesListQueryKey = () => {
  return ["expensesList"] as const;
};

export const getExpensesListQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesList>>> = ({
    signal,
  }) => expensesList({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesList>>
>;
export type ExpensesListQueryError = NotFoundErrorDTO;

export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExpensesListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateExpensesList = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getExpensesListQueryKey() },
    options,
  );

  return queryClient;
};

export const getExpensesCreateUrl = () => {
  return `/api/v1/expenses`;
};

export const expensesCreate = async (
  expenseCreateDTO: ExpenseCreateDTO,
  options?: RequestInit,
): Promise<ExpenseDTO> => {
  const res = await fetch(getExpensesCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(expenseCreateDTO),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ExpenseDTO = body ? JSON.parse(body) : {};
  return data;
};

export const getExpensesCreateMutationOptions = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesCreate>>,
    TError,
    { data: ExpenseCreateDTO },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesCreate>>,
  TError,
  { data: ExpenseCreateDTO },
  TContext
> => {
  const mutationKey = ["expensesCreate"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesCreate>>,
    { data: ExpenseCreateDTO }
  > = (props) => {
    const { data } = props ?? {};

    return expensesCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesCreate>>
>;
export type ExpensesCreateMutationBody = ExpenseCreateDTO;
export type ExpensesCreateMutationError =
  | ValidationErrorDTO
  | InternalServerErrorDTO;

export const useExpensesCreate = <
  TError = ValidationErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesCreate>>,
      TError,
      { data: ExpenseCreateDTO },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesCreate>>,
  TError,
  { data: ExpenseCreateDTO },
  TContext
> => {
  const mutationOptions = getExpensesCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getExpensesGetUrl = (expenseId: number) => {
  return `/api/v1/expenses/${expenseId}`;
};

export const expensesGet = async (
  expenseId: number,
  options?: RequestInit,
): Promise<ExpenseDTO> => {
  const res = await fetch(getExpensesGetUrl(expenseId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ExpenseDTO = body ? JSON.parse(body) : {};
  return data;
};

export const getExpensesGetQueryKey = (expenseId?: number) => {
  return ["expensesGet"] as const;
};

export const getExpensesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesGetQueryKey(expenseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesGet>>> = ({
    signal,
  }) => expensesGet(expenseId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!expenseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesGet>>
>;
export type ExpensesGetQueryError = NotFoundErrorDTO | InternalServerErrorDTO;

export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExpensesGetQueryOptions(expenseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invalidateExpensesGet = async (
  queryClient: QueryClient,
  expenseId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getExpensesGetQueryKey(expenseId) },
    options,
  );

  return queryClient;
};

export const getExpensesDeleteUrl = (expenseId: number) => {
  return `/api/v1/expenses/${expenseId}`;
};

export const expensesDelete = async (
  expenseId: number,
  options?: RequestInit,
): Promise<void> => {
  const res = await fetch(getExpensesDeleteUrl(expenseId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: void = body ? JSON.parse(body) : {};
  return data;
};

export const getExpensesDeleteMutationOptions = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesDelete>>,
    TError,
    { expenseId: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesDelete>>,
  TError,
  { expenseId: number },
  TContext
> => {
  const mutationKey = ["expensesDelete"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesDelete>>,
    { expenseId: number }
  > = (props) => {
    const { expenseId } = props ?? {};

    return expensesDelete(expenseId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesDelete>>
>;

export type ExpensesDeleteMutationError = InternalServerErrorDTO;

export const useExpensesDelete = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesDelete>>,
      TError,
      { expenseId: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesDelete>>,
  TError,
  { expenseId: number },
  TContext
> => {
  const mutationOptions = getExpensesDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
