/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ExpenseCreateDTO,
  ExpenseDTO,
  ExpenseUpdateDTO,
  ExpensesListParams,
  InternalServerErrorDTO,
  NotFoundErrorDTO,
  ValidationErrorDTO,
} from "../model";

import { fetcher } from "../../fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getExpensesListUrl = (params?: ExpensesListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/expenses?${stringifiedParams}`
    : `/api/v1/expenses`;
};

export const expensesList = async (
  params?: ExpensesListParams,
  options?: RequestInit,
): Promise<ExpenseDTO[]> => {
  return fetcher<ExpenseDTO[]>(getExpensesListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getExpensesListQueryKey = (params?: ExpensesListParams) => {
  return ["expensesList", ...(params ? [params] : [])] as const;
};

export const getExpensesListQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  params?: ExpensesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesList>>> = ({
    signal,
  }) => expensesList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesList>>
>;
export type ExpensesListQueryError = NotFoundErrorDTO;

export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  params: undefined | ExpensesListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  params?: ExpensesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesList>>,
          TError,
          Awaited<ReturnType<typeof expensesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  params?: ExpensesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExpensesList<
  TData = Awaited<ReturnType<typeof expensesList>>,
  TError = NotFoundErrorDTO,
>(
  params?: ExpensesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExpensesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateExpensesList = async (
  queryClient: QueryClient,
  params?: ExpensesListParams,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getExpensesListQueryKey(params) },
    options,
  );

  return queryClient;
};

export const getExpensesCreateUrl = () => {
  return `/api/v1/expenses`;
};

export const expensesCreate = async (
  expenseCreateDTO: ExpenseCreateDTO,
  options?: RequestInit,
): Promise<ExpenseDTO> => {
  return fetcher<ExpenseDTO>(getExpensesCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(expenseCreateDTO),
  });
};

export const getExpensesCreateMutationOptions = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesCreate>>,
    TError,
    { data: ExpenseCreateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesCreate>>,
  TError,
  { data: ExpenseCreateDTO },
  TContext
> => {
  const mutationKey = ["expensesCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesCreate>>,
    { data: ExpenseCreateDTO }
  > = (props) => {
    const { data } = props ?? {};

    return expensesCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesCreate>>
>;
export type ExpensesCreateMutationBody = ExpenseCreateDTO;
export type ExpensesCreateMutationError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export const useExpensesCreate = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesCreate>>,
      TError,
      { data: ExpenseCreateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesCreate>>,
  TError,
  { data: ExpenseCreateDTO },
  TContext
> => {
  return useMutation(getExpensesCreateMutationOptions(options), queryClient);
};
export const getExpensesGetUrl = (expenseId: number) => {
  return `/api/v1/expenses/${expenseId}`;
};

export const expensesGet = async (
  expenseId: number,
  options?: RequestInit,
): Promise<ExpenseDTO> => {
  return fetcher<ExpenseDTO>(getExpensesGetUrl(expenseId), {
    ...options,
    method: "GET",
  });
};

export const getExpensesGetQueryKey = (expenseId: number) => {
  return ["expensesGet", ...(expenseId ? [expenseId] : [])] as const;
};

export const getExpensesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesGetQueryKey(expenseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesGet>>> = ({
    signal,
  }) => expensesGet(expenseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!expenseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesGet>>
>;
export type ExpensesGetQueryError = NotFoundErrorDTO | InternalServerErrorDTO;

export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesGet>>,
          TError,
          Awaited<ReturnType<typeof expensesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExpensesGet<
  TData = Awaited<ReturnType<typeof expensesGet>>,
  TError = NotFoundErrorDTO | InternalServerErrorDTO,
>(
  expenseId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExpensesGetQueryOptions(expenseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateExpensesGet = async (
  queryClient: QueryClient,
  expenseId: number,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getExpensesGetQueryKey(expenseId) },
    options,
  );

  return queryClient;
};

export const getExpensesUpdateUrl = (expenseId: number) => {
  return `/api/v1/expenses/${expenseId}`;
};

export const expensesUpdate = async (
  expenseId: number,
  expenseUpdateDTO: ExpenseUpdateDTO,
  options?: RequestInit,
): Promise<ExpenseDTO> => {
  return fetcher<ExpenseDTO>(getExpensesUpdateUrl(expenseId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(expenseUpdateDTO),
  });
};

export const getExpensesUpdateMutationOptions = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesUpdate>>,
    TError,
    { expenseId: number; data: ExpenseUpdateDTO },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesUpdate>>,
  TError,
  { expenseId: number; data: ExpenseUpdateDTO },
  TContext
> => {
  const mutationKey = ["expensesUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesUpdate>>,
    { expenseId: number; data: ExpenseUpdateDTO }
  > = (props) => {
    const { expenseId, data } = props ?? {};

    return expensesUpdate(expenseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesUpdate>>
>;
export type ExpensesUpdateMutationBody = ExpenseUpdateDTO;
export type ExpensesUpdateMutationError =
  | ValidationErrorDTO
  | NotFoundErrorDTO
  | InternalServerErrorDTO;

export const useExpensesUpdate = <
  TError = ValidationErrorDTO | NotFoundErrorDTO | InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesUpdate>>,
      TError,
      { expenseId: number; data: ExpenseUpdateDTO },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesUpdate>>,
  TError,
  { expenseId: number; data: ExpenseUpdateDTO },
  TContext
> => {
  return useMutation(getExpensesUpdateMutationOptions(options), queryClient);
};
export const getExpensesDeleteUrl = (expenseId: number) => {
  return `/api/v1/expenses/${expenseId}`;
};

export const expensesDelete = async (
  expenseId: number,
  options?: RequestInit,
): Promise<void> => {
  return fetcher<void>(getExpensesDeleteUrl(expenseId), {
    ...options,
    method: "DELETE",
  });
};

export const getExpensesDeleteMutationOptions = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesDelete>>,
    TError,
    { expenseId: number },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesDelete>>,
  TError,
  { expenseId: number },
  TContext
> => {
  const mutationKey = ["expensesDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesDelete>>,
    { expenseId: number }
  > = (props) => {
    const { expenseId } = props ?? {};

    return expensesDelete(expenseId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesDelete>>
>;

export type ExpensesDeleteMutationError = InternalServerErrorDTO;

export const useExpensesDelete = <
  TError = InternalServerErrorDTO,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesDelete>>,
      TError,
      { expenseId: number },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesDelete>>,
  TError,
  { expenseId: number },
  TContext
> => {
  return useMutation(getExpensesDeleteMutationOptions(options), queryClient);
};
