/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const ExpensesListQueryParams = zod.object({
  days: zod.number().optional(),
});

export const expensesListResponseAmountMin = 0.01;

export const ExpensesListResponseItem = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(expensesListResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});
export const ExpensesListResponse = zod.array(ExpensesListResponseItem);

export const expensesCreateBodyAmountMin = 0.01;

export const ExpensesCreateBody = zod.object({
  amount: zod.number().min(expensesCreateBodyAmountMin),
  categoryId: zod.number().min(1),
  description: zod.string().optional(),
  date: zod.iso.datetime({}).optional(),
});

export const expensesCreateResponseAmountMin = 0.01;

export const ExpensesCreateResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(expensesCreateResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const ExpensesGetParams = zod.object({
  expenseId: zod.number(),
});

export const expensesGetResponseAmountMin = 0.01;

export const ExpensesGetResponse = zod.object({
  id: zod.number().min(1),
  accountId: zod.number().min(1),
  amount: zod.number().min(expensesGetResponseAmountMin),
  categoryId: zod.number().min(1),
  userId: zod.number().min(1),
  description: zod.union([zod.string(), zod.null()]).optional(),
  date: zod.iso.datetime({}),
});

export const ExpensesDeleteParams = zod.object({
  expenseId: zod.number(),
});
