export const FASTIFY_JWT_ERROR_CODES = {
  NO_AUTHORIZATION_IN_COOKIE: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',
  NO_AUTHORIZATION_IN_HEADER: 'FST_JWT_NO_AUTHORIZATION_IN_HEADER',
  AUTHORIZATION_TOKEN_EXPIRED: 'FST_JWT_AUTHORIZATION_TOKEN_EXPIRED',
  AUTHORIZATION_TOKEN_INVALID: 'FST_JWT_AUTHORIZATION_TOKEN_INVALID',
  AUTHORIZATION_TOKEN_UNTRUSTED: 'FST_JWT_AUTHORIZATION_TOKEN_UNTRUSTED',
  BAD_REQUEST: 'FST_JWT_BAD_REQUEST',
  BAD_COOKIE_REQUEST: 'FST_JWT_BAD_COOKIE_REQUEST'
} as const;

export type FastifyJwtErrorCode =
  (typeof FASTIFY_JWT_ERROR_CODES)[keyof typeof FASTIFY_JWT_ERROR_CODES];

export const FASTIFY_BUILTIN_ERROR_CODES = {
  VALIDATION: 'FST_ERR_VALIDATION',
  NOT_FOUND: 'FST_ERR_NOT_FOUND',
  BAD_REQUEST: 'FST_ERR_BAD_REQUEST',
  BAD_STATUS_CODE: 'FST_ERR_BAD_STATUS_CODE'
} as const;

export type FastifyBuiltinErrorCode =
  (typeof FASTIFY_BUILTIN_ERROR_CODES)[keyof typeof FASTIFY_BUILTIN_ERROR_CODES];

export const CUSTOM_ERROR_CODES = {
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  NO_ACCOUNT: 'NO_ACCOUNT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export type CustomErrorCode =
  (typeof CUSTOM_ERROR_CODES)[keyof typeof CUSTOM_ERROR_CODES];

export function isJwtError(code?: string): code is FastifyJwtErrorCode {
  return code?.startsWith('FST_JWT_') ?? false;
}

export function isValidationError(code?: string): code is 'FST_ERR_VALIDATION' {
  return code === 'FST_ERR_VALIDATION';
}
