/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface ExpenseCreate {
  /** @minimum 0.01 */
  amount: number;
  /** @minimum 1 */
  categoryId: number;
  description?: string;
  date?: string;
}
