/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { InternalServerErrorDTOCode } from "./internalServerErrorDTOCode";

export interface InternalServerErrorDTO {
  code: InternalServerErrorDTOCode;
  message: string;
}
