/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export interface LoginRequestDTO {
  /** @minimum 1 */
  auth_date: number;
  first_name: string;
  hash: string;
  /** @minimum 1 */
  id: number;
  last_name?: string;
  photo_url?: string;
  username?: string;
}
