/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NoAccountErrorDTOCode =
  (typeof NoAccountErrorDTOCode)[keyof typeof NoAccountErrorDTOCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoAccountErrorDTOCode = {
  NO_ACCOUNT: "NO_ACCOUNT",
} as const;
