/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { NotFoundErrorDTOCode } from "./notFoundErrorDTOCode";

export interface NotFoundErrorDTO {
  code: NotFoundErrorDTOCode;
  message: string;
}
