/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type NotFoundErrorCode = typeof NotFoundErrorCode[keyof typeof NotFoundErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorCode = {
  NOT_FOUND: 'NOT_FOUND',
} as const;
