/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */

export type UnauthorizedErrorDTOCode =
  (typeof UnauthorizedErrorDTOCode)[keyof typeof UnauthorizedErrorDTOCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnauthorizedErrorDTOCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_TOKEN_TYPE: "INVALID_TOKEN_TYPE",
} as const;
