/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import type { ValidationErrorCode } from './validationErrorCode';

export interface ValidationError {
  code: ValidationErrorCode;
  message: string;
  details: string[];
}
