/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Expense service
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod";

export const authLoginBody = zod.object({
  id: zod.number().min(1),
  first_name: zod.string(),
  last_name: zod.string().optional(),
  username: zod.string().optional(),
  photo_url: zod.string().optional(),
  auth_date: zod.number().min(1),
  hash: zod.string(),
});

export const authLoginResponse = zod.object({
  success: zod.boolean(),
});

export const authLogoutResponse = zod.object({
  success: zod.boolean(),
});

export const authMeResponse = zod.object({
  userId: zod.number().min(1),
  currentAccountId: zod.number().min(1),
  accounts: zod.array(
    zod.object({
      id: zod.number().min(1),
      name: zod.string(),
      isOwner: zod.boolean(),
    }),
  ),
});

export const authRefreshResponse = zod.object({
  success: zod.boolean(),
});
